#!/bin/sh

def
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start Gnome 3 Desktop 
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
#dbus-launch --exit-with-session gnome-session &

if [ -x "$(command -v cinnamon-session)" ]; then
  # linux-mint
  exec /usr/bin/cinnamon-session & 
else 
  # ubuntu 18.10 ...
  exec /usr/lib/gnome-session/gnome-session-binary --session=ubuntu & 
fi

