#!/bin/sh

PATH=/usr/bin:/usr/sbin
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start Gnome 3 Desktop 
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
#dbus-launch --exit-with-session gnome-session &

# identify the right session 'ls /usr/share/xsessions/'
# see https://stackoverflow.com/questions/59709214/tigervncserver-crashes-unless-started-with-sudo
if [ -x "$(command -v cinnamon-session-cinnamon2d)" ]; then
  # linux-mint 21.0
  exec /usr/bin/cinnamon-session-cinnamon2d & 
else 
  # ubuntu 18.10 ...
  exec /usr/lib/gnome-session/gnome-session-binary --session=ubuntu & 
fi

